apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 172.29.81.0:8083/nexus/docker/test/staging/a2odev-custom-nginx-image:1.01 # Imagen previamente subida a nexus en el proceso CI
        envFrom:
          - secretRef:
              name: doppler-test-secret # Kubernetes secret name
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort # Puedes cambiar a NodePort o ClusterIP dependiendo de tu necesidad
